# test/oracle/checks_identification.jl — identification vs BVAR_ / optional MATLAB / vars.
#
# Primary oracle: committed CSVs in identification_ref/ generated by
# octave/ref_identification.m (Ferroni-Canova BVAR_ toolbox). Tests do not
# require Octave at run time. Skip the numerical compare if those CSVs are
# absent. Uhlig MATLAB and R vars::SVAR are documented recipes; they skip
# when the external binary/package is missing (never required in CI).
#
# Run from repo root:
#     $JULIA --project=. test/oracle/checks_identification.jl
#
# Regenerate BVAR_ fixtures (optional):
#     octave --no-gui test/oracle/octave/ref_identification.m

using MacroEconometricModels, LinearAlgebra, Random, Statistics, DelimitedFiles
const MEM = MacroEconometricModels
include(joinpath(@__DIR__, "compare.jl"))

const ID_REF = joinpath(@__DIR__, "identification_ref")
const BVAR_DEFAULT = "/Users/chung/Downloads/BVAR_-master-2"

function _bvar_toolbox_present()
    haskey(ENV, "BVAR_TOOLBOX") && isdir(ENV["BVAR_TOOLBOX"]) && return true
    isdir(BVAR_DEFAULT) && isfile(joinpath(BVAR_DEFAULT, "bvartools", "iresponse_proxy.m"))
end

function _id_ref_present()
    isfile(joinpath(ID_REF, "Y.csv")) && isfile(joinpath(ID_REF, "proxy_b1.csv")) &&
        isfile(joinpath(ID_REF, "long_run_Q.csv")) && isfile(joinpath(ID_REF, "sign_impact_p16.csv"))
end

function _rscript_available()
    Sys.which("Rscript") !== nothing
end

function _vars_package_present()
    _rscript_available() || return false
    try
        out = read(`Rscript -e "cat(requireNamespace('vars', quietly=TRUE))"`, String)
        return occursin("TRUE", out)
    catch
        return false
    end
end

function _uhlig_matlab_present()
    haskey(ENV, "UHLIG_MATLAB") && isfile(ENV["UHLIG_MATLAB"])
end

function _read_id(name)
    readdlm(joinpath(ID_REF, name * ".csv"), ',', Float64)
end

function _sign_align!(a::AbstractVector, b::AbstractVector)
    dot(a, b) < 0 && (a .*= -1)
    a
end

function run_bvar_checks()
    Y = _read_id("Y")
    z = vec(_read_id("z"))
    m = estimate_var(Y, 1)

    # Proxy point estimates (Mertens-Ravn unit-variance column), rtol=1e-6.
    r = identify_proxy(m, reshape(z, :, 1); normalize=:unit_variance)
    b1 = Vector{Float64}(r.B0[:, 1])
    b1_ref = vec(_read_id("proxy_b1"))
    _sign_align!(b1, b1_ref)
    r1 = compare("proxy B0[:,1] vs BVAR_ iresponse_proxy", b1, b1_ref; rtol=1e-6, atol=1e-8)

    # Long-run impact (BVAR_ Q is the impact matrix, not the orthogonal rotation).
    Q = identify_long_run(m)
    B0_lr = Matrix{Float64}(cholesky_factor(m)) * Q
    B0_ref = _read_id("long_run_Q")
    for j in 1:size(B0_lr, 2)
        _sign_align!(view(B0_lr, :, j), view(B0_ref, :, j))
    end
    r2 = compare("long-run impact vs BVAR_ BQ Q", B0_lr, B0_ref;
                 rtol=1e-6, atol=1e-8)

    # Sign-set 16/84 impact bounds for shock 1 (Haar RNG differs; MC tolerance).
    chk = irf -> irf[1, 1, 1] > 0 && irf[1, 2, 1] > 0
    s = identify_sign(m, 8, chk; max_draws=2000, store_all=true, rng=MersenneTwister(75503))
    imps = reduce(hcat, (s.irf_draws[i, 1, :, 1] for i in 1:s.n_accepted))
    lo = [quantile(@view(imps[j, :]), 0.16) for j in 1:size(imps, 1)]
    hi = [quantile(@view(imps[j, :]), 0.84) for j in 1:size(imps, 1)]
    lo_ref = vec(_read_id("sign_impact_p16"))
    hi_ref = vec(_read_id("sign_impact_p84"))
    r3 = compare("sign-set p16 impact (shock 1)", lo, lo_ref; rtol=0.25, atol=0.20)
    r4 = compare("sign-set p84 impact (shock 1)", hi, hi_ref; rtol=0.25, atol=0.20)

    all_pass = r1.pass && r2.pass && r3.pass && r4.pass
    println("\nBVAR_ identification: ", all_pass ? "PASS" : "FAIL")
    all_pass
end

println("── Identification oracle (#755) ──")
println("BVAR_ toolbox present: ", _bvar_toolbox_present())
println("identification_ref CSVs: ", _id_ref_present())

pass = true
if _id_ref_present()
    pass = run_bvar_checks() && pass
else
    println("SKIP BVAR_ numerical compare: identification_ref CSVs absent.")
    println("  Recipe: octave --no-gui test/oracle/octave/ref_identification.m")
    if !_bvar_toolbox_present()
        println("  BVAR_ path missing (default $BVAR_DEFAULT); set BVAR_TOOLBOX if it moved.")
    end
end

if _uhlig_matlab_present()
    println("Uhlig MATLAB recipe is present at ENV[UHLIG_MATLAB]; no automated dump in this harness.")
else
    println("SKIP Uhlig MATLAB penalty: set UHLIG_MATLAB to Mountford-Uhlig (2009) replication .m")
end

if _vars_package_present()
    println("R vars package present: AB-model SVAR recipe is documented in README.md.")
else
    println("SKIP vars::SVAR: Rscript or the CRAN vars package is not available.")
end

pass || error("identification oracle comparison failed")
