# MacroEconometricModels.jl
# Copyright (C) 2025-2026 Wookyung Chung <chung@friedman.jp>
#
# This file is part of MacroEconometricModels.jl.
# Licensed under GPL-3.0-or-later. See LICENSE for details.

"""
LM unit root test with 0, 1, or 2 structural breaks.

Lee–Strazicich (2003, 2013) / Schmidt–Phillips (1992) min-LM procedure:
detrend under the null via the *differenced* regression Δy on ΔZ (not levels),
impose S̃₁ = 0 via the ψ̃_x = y₁ − Z₁'δ̃ correction, then form the LM t-stat
on S̃_{t−1} in the second-stage regression of ΔS̃. Critical values depend on
the break model (A = level/crash, C = level+trend).
"""

using LinearAlgebra, Statistics

"""
    lm_unitroot_test(y; breaks=0, regression=:level, lags=:aic, max_lags=nothing, trim=0.15) -> LMUnitRootResult

LM unit root test (Schmidt-Phillips 1992; Lee-Strazicich 2003, 2013).

Tests H₀: unit root (with breaks under H₀) against H₁: stationary.

# Arguments
- `y`: Time series vector
- `breaks`: Number of structural breaks (0, 1, or 2)
- `regression`: `:level` for intercept break (Model A), `:both` for intercept + trend break (Model C)
- `lags`: Number of augmenting lags, or `:aic`/`:bic`
- `max_lags`: Maximum lags for IC selection
- `trim`: Trimming fraction (default 0.15)

# Critical values

Published tables do not apply to a minimised statistic unless the search that
produced it matches theirs, so the critical values are simulated from the null
distribution of *this* implementation — one table per `(breaks, regression)`
pair, interpolated in 1/T over T = 100, 150, 250, 500 (`LM_UNITROOT_SIM_CV`,
regenerated by `test/oracle/gen_lm_adf2break_cvs.jl`). They are conditional on
the deterministic search design: `trim = 0.15` and no lag augmentation. Moving
`trim` away from the default, or letting `lags` select augmentation, shifts the
null distribution and the test becomes mildly conservative-to-liberal; the size
is calibrated for `lags = 0` at the default trimming.

# References
- Schmidt, P., & Phillips, P. C. B. (1992). LM tests for a unit root in the
  presence of deterministic trends. Oxford Bulletin of Economics and Statistics,
  54(3), 257-287.
- Lee, J., & Strazicich, M. C. (2003). Minimum Lagrange multiplier unit root
  test with two structural breaks. Review of Economics and Statistics, 85(4),
  1082-1089.
- Lee, J., & Strazicich, M. C. (2013). Minimum LM unit root test with one
  structural break. Economics Bulletin, 33(4), 2483-2492.
"""
function lm_unitroot_test(y::AbstractVector{T};
                           breaks::Int=0,
                           regression::Symbol=:level,
                           lags::Union{Int,Symbol}=:aic,
                           max_lags::Union{Int,Nothing}=nothing,
                           trim::Real=0.15) where {T<:AbstractFloat}
    0 <= breaks <= 2 || throw(ArgumentError("breaks must be 0, 1, or 2"))
    regression ∈ (:level, :both) || throw(ArgumentError("regression must be :level or :both"))

    n = length(y)
    n < 50 && throw(ArgumentError("Need at least 50 observations, got $n"))

    max_p = isnothing(max_lags) ? floor(Int, 12 * (n / 100)^0.25) : max_lags

    if breaks == 0
        return _lm_unitroot_nobreak(y, n, max_p, lags, regression, T)
    elseif breaks == 1
        return _lm_unitroot_1break(y, n, max_p, lags, regression, trim, T)
    else
        return _lm_unitroot_2break(y, n, max_p, lags, regression, trim, T)
    end
end

# -----------------------------------------------------------------------------
# Build level deterministics Z and differenced ΔZ for a candidate break set.
# Model A (`:level`): constant + trend + DU break dummies (crash).
# Model C (`:both`):  Model A + DT trend-break ramps.
# -----------------------------------------------------------------------------
function _lm_build_Z(n::Int, breaks_tb::Vector{Int}, regression::Symbol, ::Type{T}) where {T}
    # Level deterministics Z. Constant columns become zero after differencing;
    # they are absorbed into the ψ̃_x correction that forces S̃₁ = 0.
    trend = T.(1:n)
    if regression == :level && isempty(breaks_tb)
        # Schmidt–Phillips intercept-only: Z = 1
        Z = reshape(ones(T, n), n, 1)
    else
        # Intercept + trend (+ breaks)
        Z = hcat(ones(T, n), trend)
        for tb in breaks_tb
            DU = T.((1:n) .> tb)                 # level-shift dummy
            Z = hcat(Z, DU)
            if regression == :both
                DT = T.(max.(0, (1:n) .- tb))    # trend-break ramp
                Z = hcat(Z, DT)
            end
        end
    end
    dZ_raw = diff(Z; dims=1)
    # Indices of non-zero ΔZ columns (for the differenced regression)
    keep = Int[j for j in 1:size(dZ_raw, 2)
               if maximum(abs, view(dZ_raw, :, j)) > T(1e-12)]
    return Z, dZ_raw, keep
end

"""
Lee–Strazicich de-trending under the unit-root null:
  1. OLS of Δy on the non-zero columns of ΔZ → δ̃ (padded for zero columns)
  2. S̃_t = y_t − Z_t'δ̃ − ψ̃_x  with  ψ̃_x = y₁ − Z₁'δ̃  (forces S̃₁ = 0)
Returns (S̃, dZ_kept) where dZ_kept is the non-zero ΔZ used in the second stage.
"""
function _lm_detrend(y::AbstractVector{T}, Z::AbstractMatrix{T},
                     dZ_raw::AbstractMatrix{T}, keep::Vector{Int}) where {T<:AbstractFloat}
    n = length(y)
    dy = diff(y)
    k = size(Z, 2)
    delta = zeros(T, k)
    if !isempty(keep)
        dZ_kept = dZ_raw[:, keep]
        delta_kept = dZ_kept \ dy
        delta[keep] = delta_kept
    else
        dZ_kept = Matrix{T}(undef, n - 1, 0)
    end
    # ψ̃_x so that S̃_1 = 0
    psi = y[1] - dot(view(Z, 1, :), delta)
    S = y .- Z * delta .- psi
    return S, dZ_kept
end

"""
Second-stage LM regression: ΔS̃_t = φ S̃_{t−1} + γ' ΔZ_t + Σ_j β_j ΔS̃_{t−j} + error.
Returns (t_φ, p_used) for the best lag by `lags_spec`.
"""
function _lm_second_stage(S::AbstractVector{T}, dZ::AbstractMatrix{T},
                          max_p::Int, lags_spec::Union{Int,Symbol}) where {T<:AbstractFloat}
    n = length(S)
    dS = diff(S)                         # length n-1
    p_range = lags_spec isa Int ? [lags_spec] : collect(0:max_p)

    best_ic = T(Inf)
    best_stat = T(Inf)
    best_p = 0

    for p in p_range
        # Rows of the second-stage regression start after p lags of ΔS
        # Effective: t = p+2 … n in levels  ↔  indices p+1 … n-1 in dS
        nobs = (n - 1) - p
        nobs < 10 && continue

        Y = dS[(p+1):end]                               # ΔS̃_t
        S_lag = S[(p+1):(n-1)]                          # S̃_{t−1}

        # Score / break dummies: ΔZ over the same rows
        dZ_rows = dZ[(p+1):end, :]                      # (nobs × k)

        cols = Any[S_lag]
        size(dZ_rows, 2) > 0 && push!(cols, dZ_rows)
        if p > 0
            dS_lags = Matrix{T}(undef, nobs, p)
            for j in 1:p
                dS_lags[:, j] = dS[(p+1-j):(n-1-j)]
            end
            push!(cols, dS_lags)
        end
        X = hcat(cols...)

        XtX = X'X
        κ = cond(XtX)
        (!isfinite(κ) || κ > 1e12) && continue

        B = XtX \ (X'Y)
        resid_vec = Y - X * B
        k_params = size(X, 2)
        dof = nobs - k_params
        dof < 1 && continue
        sigma2 = sum(abs2, resid_vec) / dof
        se1 = sqrt(max(sigma2 * inv(XtX)[1, 1], zero(T)))
        stat = se1 > zero(T) ? B[1] / se1 : T(Inf)

        if lags_spec isa Symbol
            log_ssr = log(max(sum(abs2, resid_vec) / nobs, eps(T)))
            ic = lags_spec == :aic ? log_ssr + 2 * k_params / nobs :
                                     log_ssr + log(nobs) * k_params / nobs
            if ic < best_ic
                best_ic = ic
                best_stat = stat
                best_p = p
            end
        else
            best_stat = stat
            best_p = p
        end
    end
    return best_stat, best_p
end

function _lm_unitroot_nobreak(y::AbstractVector{T}, n::Int, max_p::Int,
                               lags_spec::Union{Int,Symbol}, regression::Symbol, ::Type{T}) where {T}
    Z, dZ_raw, keep = _lm_build_Z(n, Int[], regression, T)
    S, dZ = _lm_detrend(y, Z, dZ_raw, keep)
    best_stat, best_p = _lm_second_stage(S, dZ, max_p, lags_spec)

    nobs = n - 1 - best_p
    cv_row = _lm_unitroot_cv_row(0, n, regression)
    cv = _cv_dict(cv_row, T)
    pval = _break_test_pvalue(best_stat, cv_row)
    LMUnitRootResult(best_stat, pval, 0, Int[], T[], best_p, regression, cv, nobs)
end

function _lm_unitroot_1break(y::AbstractVector{T}, n::Int, max_p::Int,
                              lags_spec::Union{Int,Symbol}, regression::Symbol, trim::Real, ::Type{T}) where {T}
    start_idx = max(2, ceil(Int, trim * n))
    end_idx = min(n - 1, floor(Int, (1 - trim) * n))

    min_stat = T(Inf)
    best_break = start_idx
    best_lags = 0

    for tb in start_idx:end_idx
        Z, dZ_raw, keep = _lm_build_Z(n, [tb], regression, T)
        S, dZ = _lm_detrend(y, Z, dZ_raw, keep)
        stat_tb, p_tb = _lm_second_stage(S, dZ, max_p, lags_spec)
        if stat_tb < min_stat
            min_stat = stat_tb
            best_break = tb
            best_lags = p_tb
        end
    end

    nobs = n - 1 - best_lags
    cv_row = _lm_unitroot_cv_row(1, n, regression)
    cv = _cv_dict(cv_row, T)
    break_frac = T(best_break) / n
    pval = _break_test_pvalue(min_stat, cv_row)

    LMUnitRootResult(min_stat, pval, 1, [best_break], [break_frac], best_lags, regression, cv, nobs)
end

function _lm_unitroot_2break(y::AbstractVector{T}, n::Int, max_p::Int,
                              lags_spec::Union{Int,Symbol}, regression::Symbol, trim::Real, ::Type{T}) where {T}
    start_idx = max(2, ceil(Int, trim * n))
    end_idx = min(n - 1, floor(Int, (1 - trim) * n))
    min_gap = max(2, ceil(Int, trim * n))

    min_stat = T(Inf)
    best_tb1 = start_idx
    best_tb2 = start_idx + min_gap
    best_lags = 0

    for tb1 in start_idx:end_idx
        for tb2 in (tb1 + min_gap):end_idx
            Z, dZ_raw, keep = _lm_build_Z(n, [tb1, tb2], regression, T)
            S, dZ = _lm_detrend(y, Z, dZ_raw, keep)
            stat_tb, p_tb = _lm_second_stage(S, dZ, max_p, lags_spec)
            if stat_tb < min_stat
                min_stat = stat_tb
                best_tb1 = tb1
                best_tb2 = tb2
                best_lags = p_tb
            end
        end
    end

    nobs = n - 1 - best_lags
    cv_row = _lm_unitroot_cv_row(2, n, regression)
    cv = _cv_dict(cv_row, T)
    pval = _break_test_pvalue(min_stat, cv_row)

    LMUnitRootResult(min_stat, pval, 2, [best_tb1, best_tb2],
                     [T(best_tb1)/n, T(best_tb2)/n], best_lags, regression, cv, nobs)
end

lm_unitroot_test(y::AbstractVector; kwargs...) = lm_unitroot_test(Float64.(y); kwargs...)
