# MacroEconometricModels.jl
# Copyright (C) 2025-2026 Wookyung Chung <chung@friedman.jp>
#
# This file is part of MacroEconometricModels.jl.
# Licensed under GPL-3.0-or-later. See LICENSE for details.

"""
    SERIALIZATION_FORMAT_VERSION

On-disk schema version written into every model file by [`save_model`](@ref) and
checked by [`load_model`](@ref). Bumped only on a breaking change to the payload
layout; a file whose version this build does not recognize is rejected with a
[`SerializationError`](@ref) rather than mis-read.
"""
const SERIALIZATION_FORMAT_VERSION = 1

# Result / data types with round-trip support. Maps the stored type tag → the
# concrete type, so `load_model` dispatches `_from_serializable` on the recorded
# name. Only TOP-LEVEL `save_model` targets are listed here; nested structs are
# resolved by name at load time (see `_resolve_ser_type`) and so need no entry.
const _SERIALIZABLE_TYPES = Dict{String,Type}(
    # ── core VAR family (original T248 set) ──────────────────────────────────
    "VARModel"                      => VARModel,
    "BVARPosterior"                 => BVARPosterior,
    "RegModel"                      => RegModel,
    "LogitModel"                    => LogitModel,
    "ProbitModel"                   => ProbitModel,
    "LPModel"                       => LPModel,
    # ── data containers ──────────────────────────────────────────────────────
    "TimeSeriesData"                => TimeSeriesData,
    "PanelData"                     => PanelData,
    "CrossSectionData"              => CrossSectionData,
    "IOData"                        => IOData,
    "IOMetaData"                    => IOMetaData,
    "ExtractionResult"              => ExtractionResult,
    "PriceModelResult"              => PriceModelResult,
    "ImpactResult"                  => ImpactResult,
    "NetworkStatsResult"            => NetworkStatsResult,
    "VerticalSpecialization"        => VerticalSpecialization,
    "ExportDecomposition"           => ExportDecomposition,
    "RegionalFootprintResult"       => RegionalFootprintResult,
    "BaqaeeFarhiResult"             => BaqaeeFarhiResult,
    "ProductionNetwork"             => ProductionNetwork,
    "SDAResult"                     => SDAResult,
    "RASResult"                     => RASResult,
    "BFLocal"                       => BFLocal,
    "BFElasticities"                => BFElasticities,
    "BFShockCurve"                  => BFShockCurve,
    "BFEquilibrium"                 => BFEquilibrium,
    "BFWedgeDecomp"                 => BFWedgeDecomp,
    "BFMisallocation"               => BFMisallocation,
    # ── cointegration / VECM ─────────────────────────────────────────────────
    "VECMModel"                     => VECMModel,
    "CointRegModel"                 => CointRegModel,
    "PanelCointRegModel"            => PanelCointRegModel,
    "JohansenResult"                => JohansenResult,
    # ── panel / PVAR ─────────────────────────────────────────────────────────
    "PVARModel"                     => PVARModel,
    "PanelRegModel"                 => PanelRegModel,
    "PanelIVModel"                  => PanelIVModel,
    "PanelLogitModel"               => PanelLogitModel,
    "PanelProbitModel"              => PanelProbitModel,
    # ── ordered / multinomial choice ─────────────────────────────────────────
    "OrderedLogitModel"             => OrderedLogitModel,
    "OrderedProbitModel"            => OrderedProbitModel,
    "MultinomialLogitModel"         => MultinomialLogitModel,
    # ── local-projection variants ────────────────────────────────────────────
    "LPIVModel"                     => LPIVModel,
    "SmoothLPModel"                 => SmoothLPModel,
    "StateLPModel"                  => StateLPModel,
    "PropensityLPModel"             => PropensityLPModel,
    # ── systems / GMM ────────────────────────────────────────────────────────
    "SURModel"                      => SURModel,
    "ThreeSLSModel"                 => ThreeSLSModel,
    "GMMModel"                      => GMMModel,
    "SMMModel"                      => SMMModel,
    # ── volatility ───────────────────────────────────────────────────────────
    "ARCHModel"                     => ARCHModel,
    "GARCHModel"                    => GARCHModel,
    "EGARCHModel"                   => EGARCHModel,
    "GJRGARCHModel"                 => GJRGARCHModel,
    "APARCHModel"                   => APARCHModel,
    "CGARCHModel"                   => CGARCHModel,
    "FIGARCHModel"                  => FIGARCHModel,
    "FIEGARCHModel"                 => FIEGARCHModel,
    "IGARCHModel"                   => IGARCHModel,
    "GarchMidasModel"               => GarchMidasModel,
    "SVModel"                       => SVModel,
    "MGARCHModel"                   => MGARCHModel,
    # ── factor / FAVAR ───────────────────────────────────────────────────────
    "FactorModel"                   => FactorModel,
    "DynamicFactorModel"            => DynamicFactorModel,
    "GeneralizedDynamicFactorModel" => GeneralizedDynamicFactorModel,
    "FAVARModel"                    => FAVARModel,
    "BayesianFAVAR"                 => BayesianFAVAR,
    "StructuralDFM"                 => StructuralDFM,
    # ── ARIMA / ARDL / nonlinear / MIDAS / state space ───────────────────────
    "ARModel"                       => ARModel,
    "MAModel"                       => MAModel,
    "ARMAModel"                     => ARMAModel,
    "ARIMAModel"                    => ARIMAModel,
    "SARIMAModel"                   => SARIMAModel,
    "ARFIMAModel"                   => ARFIMAModel,
    "ARIMAOrderSelection"           => ARIMAOrderSelection,
    "GPHResult"                     => GPHResult,
    "LocalWhittleResult"            => LocalWhittleResult,
    "ARDLModel"                     => ARDLModel,
    "ARDLLongRun"                   => ARDLLongRun,
    "ARDLBoundsTest"                => ARDLBoundsTest,
    "NARDLModel"                    => NARDLModel,
    "NARDLMultipliers"              => NARDLMultipliers,
    "NARDLSymmetryTest"             => NARDLSymmetryTest,
    "PMGModel"                      => PMGModel,
    "ThresholdModel"                => ThresholdModel,
    "STARModel"                     => STARModel,
    "MSRegModel"                    => MSRegModel,
    "HansenLinearityTest"           => HansenLinearityTest,
    "MidasModel"                    => MidasModel,
    "StateSpaceModel"               => StateSpaceModel,
    # ── SVAR identification results (SID-24 / #753) ──────────────────────────
    "ProxySVARResult"               => ProxySVARResult,
    "SVARModel"                     => SVARModel,
    "MaxShareResult"                => MaxShareResult,
    "SVECResult"                    => SVECResult,
    "ICASVARResult"                 => ICASVARResult,
    "NonGaussianMLResult"           => NonGaussianMLResult,
    "NonGaussianGMMResult"          => NonGaussianGMMResult,
    "MarkovSwitchingSVARResult"     => MarkovSwitchingSVARResult,
    "GARCHSVARResult"               => GARCHSVARResult,
    "SmoothTransitionSVARResult"    => SmoothTransitionSVARResult,
    "ExternalVolatilitySVARResult"  => ExternalVolatilitySVARResult,
    "AriasSVARResult"               => AriasSVARResult,
    "UhligSVARResult"               => UhligSVARResult,
    "BayesianSetIdentifiedSVAR"     => BayesianSetIdentifiedSVAR,
    "SignIdentifiedSet"             => SignIdentifiedSet,
    "RobustBayesResult"             => RobustBayesResult,
    # ── BVAR posteriors / prior hyperparameters (RSER-02) ────────────────────
    "MFVARPosterior"                => MFVARPosterior,
    "TVPVARPosterior"               => TVPVARPosterior,
    "MinnesotaHyperparameters"      => MinnesotaHyperparameters,
    "GLPHyperparameters"            => GLPHyperparameters,
    # ── innovation accounting (RSER-03 / #776) ───────────────────────────────
    "ImpulseResponse"                   => ImpulseResponse,
    "BayesianImpulseResponse"           => BayesianImpulseResponse,
    "FEVD"                              => FEVD,
    "BayesianFEVD"                      => BayesianFEVD,
    "HistoricalDecomposition"           => HistoricalDecomposition,
    "BayesianHistoricalDecomposition"   => BayesianHistoricalDecomposition,
    "LPImpulseResponse"                 => LPImpulseResponse,
    "LPFEVD"                            => LPFEVD,
    "StructuralLP"                      => StructuralLP,
    "GrangerCausalityResult"            => GrangerCausalityResult,
    "VARStationarityResult"             => VARStationarityResult,
    "PVARStability"                     => PVARStability,
    "PVARTestResult"                    => PVARTestResult,
    "VECMGrangerResult"                 => VECMGrangerResult,
    "VECMRestrictionTest"               => VECMRestrictionTest,
    # ── forecasts / forecast evaluation (RSER-04 / #777) ─────────────────────
    "VARForecast"                       => VARForecast,
    "BVARForecast"                      => BVARForecast,
    "VECMForecast"                      => VECMForecast,
    "ARIMAForecast"                     => ARIMAForecast,
    "LPForecast"                        => LPForecast,
    "MidasForecast"                     => MidasForecast,
    "FactorForecast"                    => FactorForecast,
    "VolatilityForecast"                => VolatilityForecast,
    "ThresholdForecast"                 => ThresholdForecast,
    "STARForecast"                      => STARForecast,
    "MSForecast"                        => MSForecast,
    "ConditionalForecast"               => ConditionalForecast,
    "ForecastCondition"                 => ForecastCondition,
    "ForecastEvaluation"                => ForecastEvaluation,
    "DMTestResult"                      => DMTestResult,
    "ClarkWestResult"                   => ClarkWestResult,
    "MincerZarnowitzResult"             => MincerZarnowitzResult,
    "ForecastEncompassingResult"        => ForecastEncompassingResult,
    "ForecastCombination"               => ForecastCombination,
    # ── nowcast models / news (RSER-05 / #778) ───────────────────────────────
    "NowcastDFM"                        => NowcastDFM,
    "NowcastBVAR"                       => NowcastBVAR,
    "NowcastBridge"                     => NowcastBridge,
    "NowcastResult"                     => NowcastResult,
    "NowcastNews"                       => NowcastNews,
    "NowcastForecast"                   => NowcastForecast,
    # ── cross-section / micro (RSER-06 / #779) ───────────────────────────────
    "RobustRegModel"                    => RobustRegModel,
    "PenalizedRegModel"                 => PenalizedRegModel,
    "HeckmanModel"                      => HeckmanModel,
    "TobitModel"                        => TobitModel,
    "TruncRegModel"                     => TruncRegModel,
    "PoissonModel"                      => PoissonModel,
    "NegBinModel"                       => NegBinModel,
    "DispersionTest"                    => DispersionTest,
    "QuantileRegModel"                  => QuantileRegModel,
    "RDDResult"                         => RDDResult,
    "SelectionResult"                   => SelectionResult,
    "MarginalEffects"                   => MarginalEffects,
    "MultinomialMarginalEffects"        => MultinomialMarginalEffects,
    "OddsRatio"                         => OddsRatio,
    "InfluenceStats"                    => InfluenceStats,
    "StabilityResult"                   => StabilityResult,
    "RegDiagnosticResult"               => RegDiagnosticResult,
    "AndersonRubinTest"                 => AndersonRubinTest,
    "AndersonRubinCI"                   => AndersonRubinCI,
    "WildClusterBootstrap"              => WildClusterBootstrap,
    "PanelTestResult"                   => PanelTestResult,
    # ── DiD / event study (RSER-07 / #780) ───────────────────────────────────
    "DIDResult"                         => DIDResult,
    "EventStudyLP"                      => EventStudyLP,
    "LPDiDResult"                       => LPDiDResult,
    "BaconDecomposition"                => BaconDecomposition,
    "PretrendTestResult"                => PretrendTestResult,
    "NegativeWeightResult"              => NegativeWeightResult,
    "HonestDiDResult"                   => HonestDiDResult,
    # ── filters / spectral / nonparametric / data summary (RSER-08 / #781) ───
    "HPFilterResult"                    => HPFilterResult,
    "HamiltonFilterResult"              => HamiltonFilterResult,
    "BeveridgeNelsonResult"             => BeveridgeNelsonResult,
    "BaxterKingResult"                  => BaxterKingResult,
    "BoostedHPResult"                   => BoostedHPResult,
    "X13FilterResult"                   => X13FilterResult,
    "ACFResult"                         => ACFResult,
    "SpectralDensityResult"             => SpectralDensityResult,
    "CrossSpectrumResult"               => CrossSpectrumResult,
    "TransferFunctionResult"            => TransferFunctionResult,
    "FisherTestResult"                  => FisherTestResult,
    "BartlettWhiteNoiseResult"          => BartlettWhiteNoiseResult,
    "KernelDensity"                     => KernelDensity,
    "KernelRegression"                  => KernelRegression,
    "LowessFit"                         => LowessFit,
    "DataSummary"                       => DataSummary,
    "DataDiagnostic"                    => DataDiagnostic,
    # ── test statistics (RSER-09 / #782) ─────────────────────────────────────
    "ADFResult"                         => ADFResult,
    "KPSSResult"                        => KPSSResult,
    "PPResult"                          => PPResult,
    "ZAResult"                          => ZAResult,
    "NgPerronResult"                    => NgPerronResult,
    "DFGLSResult"                       => DFGLSResult,
    "LMUnitRootResult"                  => LMUnitRootResult,
    "ADF2BreakResult"                   => ADF2BreakResult,
    "FourierADFResult"                  => FourierADFResult,
    "FourierKPSSResult"                 => FourierKPSSResult,
    "ERSResult"                         => ERSResult,
    "HEGYResult"                        => HEGYResult,
    "VarianceRatioResult"               => VarianceRatioResult,
    "BubbleResult"                      => BubbleResult,
    "LLCResult"                         => LLCResult,
    "IPSResult"                         => IPSResult,
    "BreitungPanelResult"               => BreitungPanelResult,
    "FisherPanelResult"                 => FisherPanelResult,
    "HadriResult"                       => HadriResult,
    "PANICResult"                       => PANICResult,
    "PesaranCIPSResult"                 => PesaranCIPSResult,
    "MoonPerronResult"                  => MoonPerronResult,
    "PanelUnitRootSummary"              => PanelUnitRootSummary,
    "EngleGrangerResult"                => EngleGrangerResult,
    "PhillipsOuliarisResult"            => PhillipsOuliarisResult,
    "GregoryHansenResult"               => GregoryHansenResult,
    "PedroniResult"                     => PedroniResult,
    "KaoResult"                         => KaoResult,
    "WesterlundResult"                  => WesterlundResult,
    "FisherJohansenResult"              => FisherJohansenResult,
    "ParkAddedResult"                   => ParkAddedResult,
    "AndrewsResult"                     => AndrewsResult,
    "BaiPerronResult"                   => BaiPerronResult,
    "HansenInstabilityResult"           => HansenInstabilityResult,
    "FactorBreakResult"                 => FactorBreakResult,
    "LjungBoxResult"                    => LjungBoxResult,
    "BoxPierceResult"                   => BoxPierceResult,
    "DurbinWatsonResult"                => DurbinWatsonResult,
    "LRTestResult"                      => LRTestResult,
    "LMTestResult"                      => LMTestResult,
    "NormalityTestResult"               => NormalityTestResult,
    "NormalityTestSuite"                => NormalityTestSuite,
    "EDFTestResult"                     => EDFTestResult,
    "BDSResult"                         => BDSResult,
    "CorTestResult"                     => CorTestResult,
    "EqualityTestResult"                => EqualityTestResult,
    "DumitrescuHurlinResult"            => DumitrescuHurlinResult,
    # ── counterfactual / OPP (RSER-10 / #783) ────────────────────────────────
    "PolicyCausalEffects"               => PolicyCausalEffects,
    "PolicyRule"                        => PolicyRule,
    "PolicyLoss"                        => PolicyLoss,
    "BaselinePath"                      => BaselinePath,
    "PolicyForecast"                    => PolicyForecast,
    "WoldRepresentation"                => WoldRepresentation,
    "PolicyCounterfactual"              => PolicyCounterfactual,
    "CounterfactualMoments"             => CounterfactualMoments,
    "OPPResult"                         => OPPResult,
    "OPPSequence"                       => OPPSequence,
    "ModelBankMember"                   => ModelBankMember,
    "CounterfactualHistory"             => CounterfactualHistory,
    "SpanningDiagnostic"                => SpanningDiagnostic,
    "ForecastSufficiency"               => ForecastSufficiency,
    "PathFloorConstraint"               => PathFloorConstraint,
    "FunctionConstraint"                => FunctionConstraint,
    # ── IO / LP / GMM leftovers (RSER-11 / #784) ─────────────────────────────
    "FootprintResult"                   => FootprintResult,
    "IOMultipliers"                     => IOMultipliers,
    "LinkageResult"                     => LinkageResult,
    "IOExtension"                       => IOExtension,
    "MontielOleaPfluegerF"              => MontielOleaPfluegerF,
    "LPIVARBand"                        => LPIVARBand,
    "BSplineBasis"                      => BSplineBasis,
    "PropensityScoreConfig"             => PropensityScoreConfig,
    "GMMWeighting"                      => GMMWeighting,
    "ParameterTransform"                => ParameterTransform,
    # ── factor IC / identifiability leftovers (RSER-14 / #787) ───────────────
    "HallinLiskaResult"                 => HallinLiskaResult,
    "BaiNgQResult"                      => BaiNgQResult,
    "AmengualWatsonResult"              => AmengualWatsonResult,
    "IdentifiabilityTestResult"         => IdentifiabilityTestResult,
    # ── DSGE / HA / OLG / CT ─────────────────────────────────────────────────
    "ModelSpec"                     => ModelSpec,
    "NamedEquation"                 => NamedEquation,
    "ModelIR"                       => ModelIR,
    "IREquation"                    => IREquation,
    "IRDecl"                        => IRDecl,
    "TimingInfo"                    => TimingInfo,
    # ── DSER-04 representative-agent solutions ───────────────────────────────
    "LinearDSGE"                    => LinearDSGE,
    "DSGESolution"                  => DSGESolution,
    "PerturbationSolution"          => PerturbationSolution,
    "ProjectionSolution"            => ProjectionSolution,
    "PerfectForesightPath"          => PerfectForesightPath,
    "PrunedStateSpace"              => PrunedStateSpace,
    "DeterminacyMap"                => DeterminacyMap,
    "KalmanSmootherResult"          => KalmanSmootherResult,
    "DSGEEstimation"                => DSGEEstimation,
    "OccBinConstraint"              => OccBinConstraint,
    "OccBinRegime"                  => OccBinRegime,
    "OccBinSolution"                => OccBinSolution,
    "OccBinIRF"                     => OccBinIRF,
    # ── DSER-05 Bayesian DSGE ────────────────────────────────────────────────
    "DSGEPrior"                     => DSGEPrior,
    "DSGEStateSpace"                => DSGEStateSpace,
    "NonlinearStateSpace"           => NonlinearStateSpace,
    "ProjectionStateSpace"          => ProjectionStateSpace,
    "BayesianDSGE"                  => BayesianDSGE,
    "PosteriorMode"                 => PosteriorMode,
    "BayesianDSGESimulation"        => BayesianDSGESimulation,
    "MCMCDiagnostics"               => MCMCDiagnostics,
    "IdentificationDiagnostics"     => IdentificationDiagnostics,
    "LearningRateCheck"             => LearningRateCheck,
    "PriorPosteriorOverlap"         => PriorPosteriorOverlap,
    "PriorPredictiveResult"         => PriorPredictiveResult,
    "PosteriorPredictiveCheck"      => PosteriorPredictiveCheck,
    "PrefilterSpec"                 => PrefilterSpec,
    "ObservationTrends"             => ObservationTrends,
    # ── DSER-06 HA household problem ─────────────────────────────────────────
    "IndividualProblem"             => IndividualProblem,
    "HouseholdSystem"               => HouseholdSystem,
    # ── DSER-07 HA results ───────────────────────────────────────────────────
    "HAGrid"                        => HAGrid,
    "IncomeProcess"                 => IncomeProcess,
    "HASteadyState"                 => HASteadyState,
    "HADSGESolution"                => HADSGESolution,
    "KrusellSmithSolution"          => KrusellSmithSolution,
    "WinberryFamily"                => WinberryFamily,
    "DenHaanAccuracy"               => DenHaanAccuracy,
    "HAGridDiagnostics"             => HAGridDiagnostics,
    # ── DSER-08 SSJ blocks ───────────────────────────────────────────────────
    "SimpleBlock"                   => SimpleBlock,
    "HetBlock"                      => HetBlock,
    "MitBlock"                      => MitBlock,
    "SSJModel"                      => SSJModel,
    "SSJGEJacobian"                 => SSJGEJacobian,
    "SSJImpulseResponse"            => SSJImpulseResponse,
    # ── DSER-10 DCEGM / firms / intermediary ─────────────────────────────────
    "DCEGMProblem"                  => DCEGMProblem,
    "DCEGMSystem"                   => DCEGMSystem,
    "DCEGMSolution"                 => DCEGMSolution,
    "DCEGMDistribution"             => DCEGMDistribution,
    "DCEGMFirm"                     => DCEGMFirm,
    "DCEGMEquilibrium"              => DCEGMEquilibrium,
    "DCEGMTransition"               => DCEGMTransition,
    "FirmSystem"                    => FirmSystem,
    "KhanThomasSteadyState"         => KhanThomasSteadyState,
    "KhanThomasTransition"          => KhanThomasTransition,
    "IntermediarySystem"            => IntermediarySystem,
    "IntermediaryPE"                => IntermediaryPE,
    "IntermediarySteadyState"       => IntermediarySteadyState,
    "IntermediaryTransition"        => IntermediaryTransition,
    # ── DSER-09 OLG / continuous-time ────────────────────────────────────────
    "BlanchardOLG"                  => BlanchardOLG,
    "BlanchardOLGSteadyState"       => BlanchardOLGSteadyState,
    "BlanchardOLGSolution"          => BlanchardOLGSolution,
    "LifeCycleOLG"                  => LifeCycleOLG,
    "LifeCycleSystem"               => LifeCycleSystem,
    "LifeCycleSteadyState"          => LifeCycleSteadyState,
    "LifeCycleTransition"           => LifeCycleTransition,
    "CTPoissonIncome"               => CTPoissonIncome,
    "CTAiyagari"                    => CTAiyagari,
    "CTSteadyState"                 => CTSteadyState,
    "CTTransition"                  => CTTransition,
    "CTTwoAsset"                    => CTTwoAsset,
    "CTTwoAssetSolution"            => CTTwoAssetSolution,
    "CTTwoAssetGE"                  => CTTwoAssetGE,
    "CTTwoAssetTransition"          => CTTwoAssetTransition,
    "ContinuousHouseholdSystem"     => ContinuousHouseholdSystem,
)

# Exported concrete structs that are not top-level `save_model` targets, with a
# permanent reason. Nested structs still round-trip inside a registered parent
# via `__struct__` / `_resolve_ser_type`; they are not independent `save_model`
# targets.
const _SERIALIZATION_EXCLUDED = Dict{String,String}(
    "PlotOutput" => "rendered HTML, not a result",
    "ReproReport" => "transient reproduce() output",
    "ReproFieldDiff" => "transient reproduce() output",
    "PFWorkspace" => "particle-filter workspace",
    "SMCState" => "SMC workspace",
    "KalmanFilterStore" => "filter workspace",
    "NeweyWestEstimator" => "flattened inline by _cov_to_dict",
    "WhiteEstimator" => "flattened inline by _cov_to_dict",
    "DriscollKraayEstimator" => "flattened inline by _cov_to_dict",
    "IOSourceTable" => "download registry, not a result",
    "LeontiefModel" => "internal IO coefficient wrapper",
    "GhoshModel" => "internal IO coefficient wrapper",
    # `_X13*` internals (unexported, underscore-prefixed) are skipped by the
    # completeness walk and are neither registered nor excluded (RSER-08).
    "NoAgents" => "sentinel empty-agent NamedTuple, not a result",
    "NonlinearConstraint" => "callable nested in ModelSpec, not a top-level save_model target",
    "VariableBound" => "nested in ModelSpec, not a top-level save_model target",
    "InverseGamma1" => "flattened by Distribution codec, not a top-level save_model target",
    "LaborSupply" => "nested in IndividualProblem, not a top-level save_model target",
    "ParametricDensity" => "nested in WinberryFamily, not a top-level save_model target",
    # callable structs nested in HA / DCEGM problems (not top-level save_model targets)
    "CRRAUtility" => "callable nested in IndividualProblem, not a top-level save_model target",
    "CRRAMarginalUtility" => "callable nested in IndividualProblem, not a top-level save_model target",
    "CRRAInverseMarginalUtility" => "callable nested in IndividualProblem, not a top-level save_model target",
    "DCEGMUtility" => "callable nested in DCEGMProblem, not a top-level save_model target",
    "DCEGMIncome" => "callable nested in DCEGMProblem, not a top-level save_model target",
    # nested SVAR restriction / identification config (SID-24 serializes them
    # inside identification results; not independent save_model targets)
    "A0SignRestriction" => "nested SVAR restriction, not a top-level save_model target",
    "A0ZeroRestriction" => "nested SVAR restriction, not a top-level save_model target",
    "AplusSignRestriction" => "nested SVAR restriction, not a top-level save_model target",
    "AplusZeroRestriction" => "nested SVAR restriction, not a top-level save_model target",
    "CumulativeRestriction" => "nested SVAR restriction, not a top-level save_model target",
    "ElasticityBound" => "nested SVAR restriction, not a top-level save_model target",
    "FEVDShareRestriction" => "nested SVAR restriction, not a top-level save_model target",
    "LongRunZeroRestriction" => "nested SVAR restriction, not a top-level save_model target",
    "MagnitudeBound" => "nested SVAR restriction, not a top-level save_model target",
    "NarrativeContributionRestriction" => "nested SVAR restriction, not a top-level save_model target",
    "NarrativeShockRestriction" => "nested SVAR restriction, not a top-level save_model target",
    "SignRestriction" => "nested SVAR restriction, not a top-level save_model target",
    "ZeroRestriction" => "nested SVAR restriction, not a top-level save_model target",
    "SVARRestrictions" => "nested in identification results, not a top-level save_model target",
    "SVARPattern" => "nested in SVARModel, not a top-level save_model target",
    "IdentificationStatus" => "nested in identification results, not a top-level save_model target",
    "IdentificationMethod" => "identification registry metadata, not a result",
    "StateTransition" => "nested in StateLPModel, not a top-level save_model target",
    "ReproManifest" => "nested in randomized results, not a top-level save_model target",
)
