# MacroEconometricModels.jl
# Copyright (C) 2025-2026 Wookyung Chung <chung@friedman.jp>
#
# This file is part of MacroEconometricModels.jl.
# Licensed under GPL-3.0-or-later. See LICENSE for details.

"""
    SERIALIZATION_FORMAT_VERSION

On-disk schema version written into every model file by [`save_model`](@ref) and
checked by [`load_model`](@ref). Bumped only on a breaking change to the payload
layout; a file whose version this build does not recognize is rejected with a
[`SerializationError`](@ref) rather than mis-read.
"""
const SERIALIZATION_FORMAT_VERSION = 1

# Result / data types with round-trip support. Maps the stored type tag → the
# concrete type, so `load_model` dispatches `_from_serializable` on the recorded
# name. Only TOP-LEVEL `save_model` targets are listed here; nested structs are
# resolved by name at load time (see `_resolve_ser_type`) and so need no entry.
const _SERIALIZABLE_TYPES = Dict{String,Type}(
    # ── core VAR family (original T248 set) ──────────────────────────────────
    "VARModel"                      => VARModel,
    "BVARPosterior"                 => BVARPosterior,
    "RegModel"                      => RegModel,
    "LogitModel"                    => LogitModel,
    "ProbitModel"                   => ProbitModel,
    "LPModel"                       => LPModel,
    # ── data containers ──────────────────────────────────────────────────────
    "TimeSeriesData"                => TimeSeriesData,
    "PanelData"                     => PanelData,
    "CrossSectionData"              => CrossSectionData,
    "IOData"                        => IOData,
    "IOMetaData"                    => IOMetaData,
    "ExtractionResult"              => ExtractionResult,
    "PriceModelResult"              => PriceModelResult,
    "ImpactResult"                  => ImpactResult,
    "NetworkStatsResult"            => NetworkStatsResult,
    "VerticalSpecialization"        => VerticalSpecialization,
    "ExportDecomposition"           => ExportDecomposition,
    "RegionalFootprintResult"       => RegionalFootprintResult,
    "BaqaeeFarhiResult"             => BaqaeeFarhiResult,
    "ProductionNetwork"             => ProductionNetwork,
    "SDAResult"                     => SDAResult,
    "RASResult"                     => RASResult,
    "BFLocal"                       => BFLocal,
    "BFElasticities"                => BFElasticities,
    "BFShockCurve"                  => BFShockCurve,
    "BFEquilibrium"                 => BFEquilibrium,
    "BFWedgeDecomp"                 => BFWedgeDecomp,
    "BFMisallocation"               => BFMisallocation,
    # ── cointegration / VECM ─────────────────────────────────────────────────
    "VECMModel"                     => VECMModel,
    "CointRegModel"                 => CointRegModel,
    "PanelCointRegModel"            => PanelCointRegModel,
    "JohansenResult"                => JohansenResult,
    # ── panel / PVAR ─────────────────────────────────────────────────────────
    "PVARModel"                     => PVARModel,
    "PanelRegModel"                 => PanelRegModel,
    "PanelIVModel"                  => PanelIVModel,
    "PanelLogitModel"               => PanelLogitModel,
    "PanelProbitModel"              => PanelProbitModel,
    # ── ordered / multinomial choice ─────────────────────────────────────────
    "OrderedLogitModel"             => OrderedLogitModel,
    "OrderedProbitModel"            => OrderedProbitModel,
    "MultinomialLogitModel"         => MultinomialLogitModel,
    # ── local-projection variants ────────────────────────────────────────────
    "LPIVModel"                     => LPIVModel,
    "SmoothLPModel"                 => SmoothLPModel,
    "StateLPModel"                  => StateLPModel,
    "PropensityLPModel"             => PropensityLPModel,
    # ── systems / GMM ────────────────────────────────────────────────────────
    "SURModel"                      => SURModel,
    "ThreeSLSModel"                 => ThreeSLSModel,
    "GMMModel"                      => GMMModel,
    "SMMModel"                      => SMMModel,
    # ── volatility ───────────────────────────────────────────────────────────
    "ARCHModel"                     => ARCHModel,
    "GARCHModel"                    => GARCHModel,
    "EGARCHModel"                   => EGARCHModel,
    "GJRGARCHModel"                 => GJRGARCHModel,
    "APARCHModel"                   => APARCHModel,
    "CGARCHModel"                   => CGARCHModel,
    "FIGARCHModel"                  => FIGARCHModel,
    "FIEGARCHModel"                 => FIEGARCHModel,
    "IGARCHModel"                   => IGARCHModel,
    "GarchMidasModel"               => GarchMidasModel,
    "SVModel"                       => SVModel,
    "MGARCHModel"                   => MGARCHModel,
    # ── factor / FAVAR ───────────────────────────────────────────────────────
    "FactorModel"                   => FactorModel,
    "DynamicFactorModel"            => DynamicFactorModel,
    "GeneralizedDynamicFactorModel" => GeneralizedDynamicFactorModel,
    "FAVARModel"                    => FAVARModel,
    "BayesianFAVAR"                 => BayesianFAVAR,
    "StructuralDFM"                 => StructuralDFM,
    # ── ARIMA / ARDL / nonlinear / MIDAS / state space ───────────────────────
    "ARModel"                       => ARModel,
    "MAModel"                       => MAModel,
    "ARMAModel"                     => ARMAModel,
    "ARIMAModel"                    => ARIMAModel,
    "SARIMAModel"                   => SARIMAModel,
    "ARFIMAModel"                   => ARFIMAModel,
    "ARIMAOrderSelection"           => ARIMAOrderSelection,
    "GPHResult"                     => GPHResult,
    "LocalWhittleResult"            => LocalWhittleResult,
    "ARDLModel"                     => ARDLModel,
    "ARDLLongRun"                   => ARDLLongRun,
    "ARDLBoundsTest"                => ARDLBoundsTest,
    "NARDLModel"                    => NARDLModel,
    "NARDLMultipliers"              => NARDLMultipliers,
    "NARDLSymmetryTest"             => NARDLSymmetryTest,
    "PMGModel"                      => PMGModel,
    "ThresholdModel"                => ThresholdModel,
    "STARModel"                     => STARModel,
    "MSRegModel"                    => MSRegModel,
    "HansenLinearityTest"           => HansenLinearityTest,
    "MidasModel"                    => MidasModel,
    "StateSpaceModel"               => StateSpaceModel,
    # ── SVAR identification results (SID-24 / #753) ──────────────────────────
    "ProxySVARResult"               => ProxySVARResult,
    "SVARModel"                     => SVARModel,
    "MaxShareResult"                => MaxShareResult,
    "SVECResult"                    => SVECResult,
    "ICASVARResult"                 => ICASVARResult,
    "NonGaussianMLResult"           => NonGaussianMLResult,
    "NonGaussianGMMResult"          => NonGaussianGMMResult,
    "MarkovSwitchingSVARResult"     => MarkovSwitchingSVARResult,
    "GARCHSVARResult"               => GARCHSVARResult,
    "SmoothTransitionSVARResult"    => SmoothTransitionSVARResult,
    "ExternalVolatilitySVARResult"  => ExternalVolatilitySVARResult,
    "AriasSVARResult"               => AriasSVARResult,
    "UhligSVARResult"               => UhligSVARResult,
    "BayesianSetIdentifiedSVAR"     => BayesianSetIdentifiedSVAR,
    "SignIdentifiedSet"             => SignIdentifiedSet,
    "RobustBayesResult"             => RobustBayesResult,
    # ── BVAR posteriors / prior hyperparameters (RSER-02) ────────────────────
    "MFVARPosterior"                => MFVARPosterior,
    "TVPVARPosterior"               => TVPVARPosterior,
    "MinnesotaHyperparameters"      => MinnesotaHyperparameters,
    "GLPHyperparameters"            => GLPHyperparameters,
    # ── innovation accounting (RSER-03 / #776) ───────────────────────────────
    "ImpulseResponse"                   => ImpulseResponse,
    "BayesianImpulseResponse"           => BayesianImpulseResponse,
    "FEVD"                              => FEVD,
    "BayesianFEVD"                      => BayesianFEVD,
    "HistoricalDecomposition"           => HistoricalDecomposition,
    "BayesianHistoricalDecomposition"   => BayesianHistoricalDecomposition,
    "LPImpulseResponse"                 => LPImpulseResponse,
    "LPFEVD"                            => LPFEVD,
    "StructuralLP"                      => StructuralLP,
    "GrangerCausalityResult"            => GrangerCausalityResult,
    "VARStationarityResult"             => VARStationarityResult,
    "PVARStability"                     => PVARStability,
    "PVARTestResult"                    => PVARTestResult,
    "VECMGrangerResult"                 => VECMGrangerResult,
    "VECMRestrictionTest"               => VECMRestrictionTest,
    # ── forecasts / forecast evaluation (RSER-04 / #777) ─────────────────────
    "VARForecast"                       => VARForecast,
    "BVARForecast"                      => BVARForecast,
    "VECMForecast"                      => VECMForecast,
    "ARIMAForecast"                     => ARIMAForecast,
    "LPForecast"                        => LPForecast,
    "MidasForecast"                     => MidasForecast,
    "FactorForecast"                    => FactorForecast,
    "VolatilityForecast"                => VolatilityForecast,
    "ThresholdForecast"                 => ThresholdForecast,
    "STARForecast"                      => STARForecast,
    "MSForecast"                        => MSForecast,
    "ConditionalForecast"               => ConditionalForecast,
    "ForecastCondition"                 => ForecastCondition,
    "ForecastEvaluation"                => ForecastEvaluation,
    "DMTestResult"                      => DMTestResult,
    "ClarkWestResult"                   => ClarkWestResult,
    "MincerZarnowitzResult"             => MincerZarnowitzResult,
    "ForecastEncompassingResult"        => ForecastEncompassingResult,
    "ForecastCombination"               => ForecastCombination,
    # ── nowcast models / news (RSER-05 / #778) ───────────────────────────────
    "NowcastDFM"                        => NowcastDFM,
    "NowcastBVAR"                       => NowcastBVAR,
    "NowcastBridge"                     => NowcastBridge,
    "NowcastResult"                     => NowcastResult,
    "NowcastNews"                       => NowcastNews,
    "NowcastForecast"                   => NowcastForecast,
)

# Exported concrete structs that are not top-level `save_model` targets, with a
# reason. Permanent keys are never saveable; `"pending DSER-NN"` / `"pending
# RSER-NN"` entries are deleted by the issue that registers those types.
const _SERIALIZATION_EXCLUDED = Dict{String,String}(
    "PlotOutput" => "rendered HTML, not a result",
    "ReproReport" => "transient reproduce() output",
    "ReproFieldDiff" => "transient reproduce() output",
    "PFWorkspace" => "particle-filter workspace",
    "SMCState" => "SMC workspace",
    "KalmanFilterStore" => "filter workspace",
    "NeweyWestEstimator" => "flattened inline by _cov_to_dict",
    "WhiteEstimator" => "flattened inline by _cov_to_dict",
    "DriscollKraayEstimator" => "flattened inline by _cov_to_dict",
    "IOSourceTable" => "download registry, not a result",
    "LeontiefModel" => "internal IO coefficient wrapper",
    "GhoshModel" => "internal IO coefficient wrapper",
    # pending DSER-02
    "ModelIR" => "pending DSER-02",
    "ModelSpec" => "pending DSER-02",
    "NamedEquation" => "pending DSER-02",
    "NoAgents" => "pending DSER-02",
    # pending DSER-04
    "DSGEEstimation" => "pending DSER-04",
    "DSGESolution" => "pending DSER-04",
    "DeterminacyMap" => "pending DSER-04",
    "KalmanSmootherResult" => "pending DSER-04",
    "LinearDSGE" => "pending DSER-04",
    "NonlinearConstraint" => "pending DSER-04",
    "OccBinConstraint" => "pending DSER-04",
    "OccBinIRF" => "pending DSER-04",
    "OccBinRegime" => "pending DSER-04",
    "OccBinSolution" => "pending DSER-04",
    "PerfectForesightPath" => "pending DSER-04",
    "PerturbationSolution" => "pending DSER-04",
    "ProjectionSolution" => "pending DSER-04",
    "PrunedStateSpace" => "pending DSER-04",
    "VariableBound" => "pending DSER-04",
    # pending DSER-05
    "BayesianDSGE" => "pending DSER-05",
    "BayesianDSGESimulation" => "pending DSER-05",
    "IdentificationDiagnostics" => "pending DSER-05",
    "InverseGamma1" => "pending DSER-05",
    "LearningRateCheck" => "pending DSER-05",
    "MCMCDiagnostics" => "pending DSER-05",
    "ObservationTrends" => "pending DSER-05",
    "PosteriorMode" => "pending DSER-05",
    "PosteriorPredictiveCheck" => "pending DSER-05",
    "PrefilterSpec" => "pending DSER-05",
    "PriorPosteriorOverlap" => "pending DSER-05",
    "PriorPredictiveResult" => "pending DSER-05",
    # pending DSER-06
    "IndividualProblem" => "pending DSER-06",
    "LaborSupply" => "pending DSER-06",
    # pending DSER-07
    "DenHaanAccuracy" => "pending DSER-07",
    "HADSGESolution" => "pending DSER-07",
    "HAGrid" => "pending DSER-07",
    "HAGridDiagnostics" => "pending DSER-07",
    "HASteadyState" => "pending DSER-07",
    "HouseholdSystem" => "pending DSER-07",
    "IncomeProcess" => "pending DSER-07",
    "KrusellSmithSolution" => "pending DSER-07",
    "ParametricDensity" => "pending DSER-07",
    "WinberryFamily" => "pending DSER-07",
    # pending DSER-08
    "HetBlock" => "pending DSER-08",
    "MitBlock" => "pending DSER-08",
    "SSJGEJacobian" => "pending DSER-08",
    "SSJImpulseResponse" => "pending DSER-08",
    "SSJModel" => "pending DSER-08",
    "SimpleBlock" => "pending DSER-08",
    # pending DSER-09
    "BlanchardOLG" => "pending DSER-09",
    "BlanchardOLGSolution" => "pending DSER-09",
    "BlanchardOLGSteadyState" => "pending DSER-09",
    "CTAiyagari" => "pending DSER-09",
    "CTPoissonIncome" => "pending DSER-09",
    "CTSteadyState" => "pending DSER-09",
    "CTTransition" => "pending DSER-09",
    "CTTwoAsset" => "pending DSER-09",
    "CTTwoAssetGE" => "pending DSER-09",
    "CTTwoAssetSolution" => "pending DSER-09",
    "CTTwoAssetTransition" => "pending DSER-09",
    "ContinuousHouseholdSystem" => "pending DSER-09",
    "LifeCycleOLG" => "pending DSER-09",
    "LifeCycleSteadyState" => "pending DSER-09",
    "LifeCycleSystem" => "pending DSER-09",
    "LifeCycleTransition" => "pending DSER-09",
    # pending DSER-10
    "DCEGMDistribution" => "pending DSER-10",
    "DCEGMEquilibrium" => "pending DSER-10",
    "DCEGMFirm" => "pending DSER-10",
    "DCEGMProblem" => "pending DSER-10",
    "DCEGMSolution" => "pending DSER-10",
    "DCEGMSystem" => "pending DSER-10",
    "DCEGMTransition" => "pending DSER-10",
    "FirmSystem" => "pending DSER-10",
    "IntermediaryPE" => "pending DSER-10",
    "IntermediarySteadyState" => "pending DSER-10",
    "IntermediarySystem" => "pending DSER-10",
    "IntermediaryTransition" => "pending DSER-10",
    "KhanThomasSteadyState" => "pending DSER-10",
    "KhanThomasTransition" => "pending DSER-10",
    # pending RSER-06
    "AndersonRubinCI" => "pending RSER-06",
    "AndersonRubinTest" => "pending RSER-06",
    "DispersionTest" => "pending RSER-06",
    "HeckmanModel" => "pending RSER-06",
    "InfluenceStats" => "pending RSER-06",
    "MarginalEffects" => "pending RSER-06",
    "MultinomialMarginalEffects" => "pending RSER-06",
    "NegBinModel" => "pending RSER-06",
    "OddsRatio" => "pending RSER-06",
    "PanelTestResult" => "pending RSER-06",
    "PenalizedRegModel" => "pending RSER-06",
    "PoissonModel" => "pending RSER-06",
    "QuantileRegModel" => "pending RSER-06",
    "RDDResult" => "pending RSER-06",
    "RegDiagnosticResult" => "pending RSER-06",
    "RobustRegModel" => "pending RSER-06",
    "SelectionResult" => "pending RSER-06",
    "StabilityResult" => "pending RSER-06",
    "TobitModel" => "pending RSER-06",
    "TruncRegModel" => "pending RSER-06",
    "WildClusterBootstrap" => "pending RSER-06",
    # pending RSER-07
    "BaconDecomposition" => "pending RSER-07",
    "DIDResult" => "pending RSER-07",
    "EventStudyLP" => "pending RSER-07",
    "HonestDiDResult" => "pending RSER-07",
    "LPDiDResult" => "pending RSER-07",
    "NegativeWeightResult" => "pending RSER-07",
    "PretrendTestResult" => "pending RSER-07",
    # pending RSER-08
    "ACFResult" => "pending RSER-08",
    "BartlettWhiteNoiseResult" => "pending RSER-08",
    "BaxterKingResult" => "pending RSER-08",
    "BeveridgeNelsonResult" => "pending RSER-08",
    "BoostedHPResult" => "pending RSER-08",
    "CrossSpectrumResult" => "pending RSER-08",
    "DataDiagnostic" => "pending RSER-08",
    "DataSummary" => "pending RSER-08",
    "FisherTestResult" => "pending RSER-08",
    "HPFilterResult" => "pending RSER-08",
    "HamiltonFilterResult" => "pending RSER-08",
    "KernelDensity" => "pending RSER-08",
    "KernelRegression" => "pending RSER-08",
    "LowessFit" => "pending RSER-08",
    "SpectralDensityResult" => "pending RSER-08",
    "TransferFunctionResult" => "pending RSER-08",
    "X13FilterResult" => "pending RSER-08",
    # pending RSER-09
    "ADF2BreakResult" => "pending RSER-09",
    "ADFResult" => "pending RSER-09",
    "AndrewsResult" => "pending RSER-09",
    "BDSResult" => "pending RSER-09",
    "BaiPerronResult" => "pending RSER-09",
    "BoxPierceResult" => "pending RSER-09",
    "BreitungPanelResult" => "pending RSER-09",
    "BubbleResult" => "pending RSER-09",
    "CorTestResult" => "pending RSER-09",
    "DFGLSResult" => "pending RSER-09",
    "DumitrescuHurlinResult" => "pending RSER-09",
    "DurbinWatsonResult" => "pending RSER-09",
    "EDFTestResult" => "pending RSER-09",
    "ERSResult" => "pending RSER-09",
    "EngleGrangerResult" => "pending RSER-09",
    "EqualityTestResult" => "pending RSER-09",
    "FactorBreakResult" => "pending RSER-09",
    "FisherJohansenResult" => "pending RSER-09",
    "FisherPanelResult" => "pending RSER-09",
    "FourierADFResult" => "pending RSER-09",
    "FourierKPSSResult" => "pending RSER-09",
    "GregoryHansenResult" => "pending RSER-09",
    "HEGYResult" => "pending RSER-09",
    "HadriResult" => "pending RSER-09",
    "HansenInstabilityResult" => "pending RSER-09",
    "IPSResult" => "pending RSER-09",
    "KPSSResult" => "pending RSER-09",
    "KaoResult" => "pending RSER-09",
    "LLCResult" => "pending RSER-09",
    "LMTestResult" => "pending RSER-09",
    "LMUnitRootResult" => "pending RSER-09",
    "LRTestResult" => "pending RSER-09",
    "LjungBoxResult" => "pending RSER-09",
    "MoonPerronResult" => "pending RSER-09",
    "NgPerronResult" => "pending RSER-09",
    "NormalityTestResult" => "pending RSER-09",
    "NormalityTestSuite" => "pending RSER-09",
    "PANICResult" => "pending RSER-09",
    "PPResult" => "pending RSER-09",
    "PanelUnitRootSummary" => "pending RSER-09",
    "ParkAddedResult" => "pending RSER-09",
    "PedroniResult" => "pending RSER-09",
    "PesaranCIPSResult" => "pending RSER-09",
    "PhillipsOuliarisResult" => "pending RSER-09",
    "VarianceRatioResult" => "pending RSER-09",
    "WesterlundResult" => "pending RSER-09",
    "ZAResult" => "pending RSER-09",
    # pending RSER-10
    "BaselinePath" => "pending RSER-10",
    "CounterfactualHistory" => "pending RSER-10",
    "CounterfactualMoments" => "pending RSER-10",
    "ForecastSufficiency" => "pending RSER-10",
    "FunctionConstraint" => "pending RSER-10",
    "ModelBankMember" => "pending RSER-10",
    "OPPResult" => "pending RSER-10",
    "OPPSequence" => "pending RSER-10",
    "PathFloorConstraint" => "pending RSER-10",
    "PolicyCausalEffects" => "pending RSER-10",
    "PolicyCounterfactual" => "pending RSER-10",
    "PolicyForecast" => "pending RSER-10",
    "PolicyLoss" => "pending RSER-10",
    "PolicyRule" => "pending RSER-10",
    "SpanningDiagnostic" => "pending RSER-10",
    "WoldRepresentation" => "pending RSER-10",
    # pending RSER-11
    "A0SignRestriction" => "pending RSER-11",
    "A0ZeroRestriction" => "pending RSER-11",
    "AmengualWatsonResult" => "pending RSER-11",
    "AplusSignRestriction" => "pending RSER-11",
    "AplusZeroRestriction" => "pending RSER-11",
    "BSplineBasis" => "pending RSER-11",
    "BaiNgQResult" => "pending RSER-11",
    "CumulativeRestriction" => "pending RSER-11",
    "ElasticityBound" => "pending RSER-11",
    "FEVDShareRestriction" => "pending RSER-11",
    "FootprintResult" => "pending RSER-11",
    "GMMWeighting" => "pending RSER-11",
    "HallinLiskaResult" => "pending RSER-11",
    "IOExtension" => "pending RSER-11",
    "IdentifiabilityTestResult" => "pending RSER-11",
    "IdentificationMethod" => "pending RSER-11",
    "IdentificationStatus" => "pending RSER-11",
    "LPIVARBand" => "pending RSER-11",
    "LongRunZeroRestriction" => "pending RSER-11",
    "MagnitudeBound" => "pending RSER-11",
    "MontielOleaPfluegerF" => "pending RSER-11",
    "NarrativeContributionRestriction" => "pending RSER-11",
    "NarrativeShockRestriction" => "pending RSER-11",
    "ParameterTransform" => "pending RSER-11",
    "PropensityScoreConfig" => "pending RSER-11",
    "ReproManifest" => "pending RSER-11",
    "SVARPattern" => "pending RSER-11",
    "SVARRestrictions" => "pending RSER-11",
    "SignRestriction" => "pending RSER-11",
    "StateTransition" => "pending RSER-11",
    "ZeroRestriction" => "pending RSER-11",
)
