# MacroEconometricModels.jl
# Copyright (C) 2025-2026 Wookyung Chung <chung@friedman.jp>
#
# This file is part of MacroEconometricModels.jl.
# Licensed under GPL-3.0-or-later. See LICENSE for details.
#
# EV-33 (#441): Nonparametric regression & density — kernel density, Nadaraya–
# Watson/local-polynomial regression, LOWESS.
#
# Oracle discipline (per test/oracle/ convention): every hard-coded reference
# value carries the EXACT R call that produced it, run LIVE in this environment
# (R 4.5.0 with stats + KernSmooth). Deterministic data are generated by
# formulas reproducible verbatim in R, so R and Julia see identical doubles.

using Test, MacroEconometricModels, Random, LinearAlgebra, Statistics

const _NP = MacroEconometricModels

# --- deterministic data (identical formulas usable in R) ---------------------
# xd <- sin(0.3*(1:60)) + 0.5*cos(0.7*(1:60))
_xd() = sin.(0.3 .* (1:60)) .+ 0.5 .* cos.(0.7 .* (1:60))
# xr <- (1:50)/10 ;  yr <- sin(xr) + 0.2*sin(11*(1:50))
_xr() = (1:50) ./ 10
_yr() = sin.((1:50) ./ 10) .+ 0.2 .* sin.(11 .* (1:50))

@testset "Nonparametric regression & density (EV-33)" begin

    @testset "Bandwidth — Silverman vs R bw.nrd0" begin
        xd = _xd()
        kd = kernel_density(xd; bw=:silverman)
        # R:  bw.nrd0(sin(0.3*(1:60)) + 0.5*cos(0.7*(1:60)))  ==  0.322083679465445
        @test kd.bandwidth ≈ 0.322083679465445 rtol = 1e-10
        @test kd.bw_method === :silverman
        # closed-form invariance: 0.9 * min(sd, IQR/1.349) * n^(-1/5)
        h_manual = 0.9 * min(std(xd), (quantile(xd, 0.75) - quantile(xd, 0.25)) / 1.349) * 60.0^(-0.2)
        @test kd.bandwidth ≈ h_manual rtol = 1e-12
    end

    @testset "Bandwidth — Sheather–Jones vs R bw.SJ" begin
        xd = _xd()
        kd = kernel_density(xd; bw=:sj)
        # R:  bw.SJ(sin(0.3*(1:60)) + 0.5*cos(0.7*(1:60)), method="ste")  ==  0.412762995192446
        # (R bins onto 1000 cells + uniroot tol; here exact pairwise φ4/φ6 + tight
        #  bisection — agreement to < 3e-3 absolute.)
        @test kd.bandwidth ≈ 0.412762995192446 atol = 3e-3
        @test kd.bw_method === :sj
        # SJ bandwidth is wider than Silverman for this heavily-structured sample
        @test kd.bandwidth > kernel_density(xd; bw=:silverman).bandwidth
    end

    @testset "Kernel density — integrates to ~1 (trapezoid)" begin
        yr = _yr()
        for k in (:gaussian, :epanechnikov, :triangular, :uniform)
            kd = kernel_density(yr; kernel=k, npoints=2000)
            dx = kd.x[2] - kd.x[1]
            integ = sum(kd.density) * dx - 0.5 * (kd.density[1] + kd.density[end]) * dx
            @test integ ≈ 1.0 atol = 2e-3
            @test all(kd.density .>= 0)
        end
        # numeric bandwidth path
        kd = kernel_density(yr; bw=0.4)
        @test kd.bandwidth == 0.4
        @test kd.bw_method === :user
    end

    @testset "LOWESS — vs R stats::lowess" begin
        xr = _xr(); yr = _yr()
        lf = lowess(yr, xr; f=2/3, iter=3)
        # R:  lowess(x=(1:50)/10, y=sin((1:50)/10)+0.2*sin(11*(1:50)), f=2/3, iter=3)$y
        # (values sorted by x; a few probe points hard-coded)
        R_y = Dict(
            1  => 0.443150123025807,
            12 => 0.716170468248574,
            17 => 0.800600144361018,
            30 => 0.115331696881568,
            36 => -0.348417258499707,
            50 => -1.259550252544159,
        )
        for (i, yv) in R_y
            @test lf.fitted[i] ≈ yv atol = 1e-8
        end
        @test lf.x == collect(xr)                     # returned sorted by x
        @test lf.span == 2/3
        @test lf.iter == 3
        # unsorted input is sorted internally and gives the same fit
        perm = shuffle(MersenneTwister(7), 1:50)
        lf2 = lowess(yr[perm], xr[perm]; f=2/3, iter=3)
        @test lf2.fitted ≈ lf.fitted atol = 1e-10
    end

    @testset "Local-linear regression — vs R KernSmooth::locpoly" begin
        xr = _xr(); yr = _yr()
        # R:  locpoly(xr, yr, degree=1, bandwidth=0.5, gridsize=401, range.x=c(0.1,5.0))
        #     probed at the fine-binning grid abscissae below (≈ exact local linear).
        oracle = [
            (0.994250000000000,  0.750625178532608),
            (1.998750000000000,  0.803002692330571),
            (3.003250000000000,  0.121717476091476),
            (3.995500000000000, -0.676999628805712),
        ]
        for (x0, yref) in oracle
            ℓ = _NP._local_weights(collect(Float64, xr), x0, 0.5, 1, :gaussian)
            @test dot(ℓ, yr) ≈ yref atol = 1e-3
        end
    end

    @testset "kernel_reg — huge bandwidth ⇒ global mean" begin
        xr = _xr(); yr = _yr()
        kr = kernel_reg(yr, xr; method=:nw, bw=1e6)
        @test all(f -> isapprox(f, mean(yr); atol=1e-6), kr.fitted)
    end

    @testset "kernel_reg — tiny bandwidth ⇒ interpolates design points" begin
        xr = _xr(); yr = _yr()
        for m in (:nw, :ll)
            kr = kernel_reg(yr, xr; method=m, bw=1e-3)
            @test maximum(abs.(kr.fitted .- kr.ydata)) < 1e-8
        end
        # local polynomial degree 2 also interpolates at a tiny bandwidth
        krp = kernel_reg(yr, xr; method=:lp, degree=2, bw=1e-3)
        @test maximum(abs.(krp.fitted .- krp.ydata)) < 1e-8
    end

    @testset "kernel_reg — CV bandwidth & sandwich bands" begin
        xr = _xr(); yr = _yr()
        kr = kernel_reg(yr, xr; method=:ll, bw=:cv)
        @test kr.bw_method === :cv
        @test kr.bandwidth > 0
        @test length(kr.se) == 50
        @test all(kr.se .>= 0)
        @test kr.sigma2 > 0
        # rule-of-thumb path
        krr = kernel_reg(yr, xr; method=:nw, bw=:rot)
        @test krr.bw_method === :rot
        @test krr.bandwidth ≈ _NP._bw_silverman(collect(Float64, xr)) rtol = 1e-12
        # sorted design points
        @test issorted(kr.x)
    end

    @testset "Error handling & argument validation" begin
        xr = _xr(); yr = _yr()
        @test_throws ArgumentError kernel_density(yr; kernel=:bogus)
        @test_throws ArgumentError kernel_density(yr; bw=:bogus)
        @test_throws ArgumentError kernel_density(yr; bw=-1.0)
        @test_throws ArgumentError kernel_density([1.0])            # < 2 obs
        @test_throws ArgumentError kernel_reg(yr, xr; method=:bogus)
        @test_throws ArgumentError kernel_reg(yr, xr; bw=:bogus)
        @test_throws DimensionMismatch kernel_reg(yr, xr[1:49])
        @test_throws DimensionMismatch lowess(yr, xr[1:49])
    end

    @testset "Display / report / refs render" begin
        xr = _xr(); yr = _yr()
        kd = kernel_density(yr; bw=:sj)
        kr = kernel_reg(yr, xr; method=:ll, bw=0.4)
        lf = lowess(yr, xr)
        for obj in (kd, kr, lf)
            s = sprint(show, obj)
            @test !isempty(s)
            @test occursin("\n", s)
            rbuf = sprint(io -> refs(io, obj))
            @test !isempty(rbuf)
            @test report(obj) === nothing            # report prints, returns nothing
        end
        @test occursin("Kernel Density", sprint(show, kd))
        @test occursin("LOWESS", sprint(show, lf))
        # bibtex format for the density refs
        @test occursin("sheather_jones1991", sprint(io -> refs(io, kd; format=:bibtex)))
    end

    @testset "plot_result — scatter + fit charts" begin
        xr = _xr(); yr = _yr()
        p1 = plot_result(kernel_density(yr))
        p2 = plot_result(kernel_reg(yr, xr; method=:ll, bw=0.4))
        p3 = plot_result(lowess(yr, xr))
        for p in (p1, p2, p3)
            @test p isa MacroEconometricModels.PlotOutput
            @test occursin("svg", p.html)
        end
        # regression chart embeds both scatter points and the fit path
        @test occursin("circle", p2.html)
        @test occursin("path", p2.html)
        # band toggle
        p2nb = plot_result(kernel_reg(yr, xr; method=:ll, bw=0.4); bands=false)
        @test p2nb isa MacroEconometricModels.PlotOutput
    end
end
