# MacroEconometricModels.jl
# Copyright (C) 2025-2026 Wookyung Chung <chung@friedman.jp>
#
# This file is part of MacroEconometricModels.jl.
# Licensed under GPL-3.0-or-later. See LICENSE for details.
#
# EV-31 (#439): OLS residual diagnostics — White, Breusch-Pagan/Koenker,
# Glejser, Harvey, Breusch-Godfrey, Ramsey RESET.

using Test
using MacroEconometricModels
using MacroEconometricModels: white_test, breusch_pagan_test, glejser_test,
    harvey_test, breusch_godfrey_test, reset_test, RegDiagnosticResult,
    _aux_centered_r2, _nonintercept_cols
using LinearAlgebra, Statistics, Random, Distributions, DataFrames, DelimitedFiles

# =============================================================================
# Fixed oracle DGP. n=200, heteroskedastic errors: sd = 0.5 + 0.8|x1|.
#   rng = MersenneTwister(20260716)
#   x1 = randn(rng,n); x2 = randn(rng,n)
#   u  = (0.5 .+ 0.8 .* abs.(x1)) .* randn(rng,n)
#   y  = 1 .+ 2x1 .- x2 .+ u
# The full (y,x1,x2) matrix was written to CSV and read by base R `lm`, which
# recomputed each auxiliary regression's nR² / F independently (an independent
# OLS engine). MersenneTwister is NOT stable across Julia versions, so the exact
# (y,x1,x2) that R saw is committed as data/reg_diag_oracle.csv (generated by
# test/gen_ev_fixtures.jl) and loaded verbatim here — the tests are thus
# reproducible on every Julia version, not just the one that made the oracle.
# =============================================================================
function _diag_oracle_dgp()
    d = readdlm(joinpath(@__DIR__, "data", "reg_diag_oracle.csv"), ',', Float64)
    y = d[:, 1]
    X = hcat(ones(size(d, 1)), d[:, 2], d[:, 3])
    (y, X)
end

@testset "Reg Diagnostics (EV-31)" begin

    y, X = _diag_oracle_dgp()
    m = estimate_reg(y, X; varnames = ["const", "x1", "x2"])

    # -------------------------------------------------------------------------
    # 1. R cross-implementation oracle (base R `lm`, R 4.5.0).
    #    Provenance for each (exact aux regression given in comments):
    #      e <- resid(lm(y ~ x1 + x2)); n <- 200; sigma2 <- sum(e^2)/n
    # -------------------------------------------------------------------------
    @testset "R oracle (base lm, R 4.5.0)" begin
        # White w/ cross: lm(I(e^2) ~ x1+x2+I(x1^2)+I(x2^2)+I(x1*x2)); nR2, df=5
        w = white_test(m; cross_terms = true)
        @test w.df == 5
        @test isapprox(w.statistic, 34.5047242749; atol = 1e-4)
        @test isapprox(w.pvalue, 0.0000018889; atol = 1e-8)

        # White no cross: lm(I(e^2) ~ x1+x2+I(x1^2)+I(x2^2)); nR2, df=4
        wn = white_test(m; cross_terms = false)
        @test wn.df == 4
        @test isapprox(wn.statistic, 26.8654212671; atol = 1e-4)
        @test isapprox(wn.pvalue, 0.0000211639; atol = 1e-8)

        # BP Koenker (studentized): lm(I(e^2) ~ x1+x2); nR2, df=2
        # == lmtest::bptest(m, studentize=TRUE)
        bp = breusch_pagan_test(m; studentized = true)
        @test bp.df == 2
        @test isapprox(bp.statistic, 4.9787264064; atol = 1e-4)
        @test isapprox(bp.pvalue, 0.0829627802; atol = 1e-7)

        # BP original: 0.5*ESS from lm(e^2/sigma2 ~ x1+x2); df=2
        bp0 = breusch_pagan_test(m; studentized = false)
        @test bp0.df == 2
        @test isapprox(bp0.statistic, 14.7454547128; atol = 1e-4)
        @test isapprox(bp0.pvalue, 0.0006281526; atol = 1e-7)

        # Glejser: F-test of lm(abs(e) ~ x1+x2); F(2,197)
        g = glejser_test(m)
        @test g.df == (2, 197)
        @test isapprox(g.statistic, 2.3840768340; atol = 1e-4)
        @test isapprox(g.pvalue, 0.0948287919; atol = 1e-6)

        # Harvey: lm(log(e^2) ~ x1+x2); nR2, df=2
        h = harvey_test(m)
        @test h.df == 2
        @test isapprox(h.statistic, 3.3420887286; atol = 1e-4)
        @test isapprox(h.pvalue, 0.1880505697; atol = 1e-6)

        # Breusch-Godfrey lags=2: lm(e ~ x1+x2+lag1+lag2), zero-padded; nR2 df=2
        # F-form: restricted lm(e~x1+x2) vs unrestricted; F(2,195)
        bg = breusch_godfrey_test(m; lags = 2)
        @test bg.df == 2
        @test isapprox(bg.statistic, 1.2121248188; atol = 1e-4)
        @test isapprox(bg.pvalue, 0.5454945801; atol = 1e-6)
        @test bg.f_df == (2, 195)
        @test isapprox(bg.f_stat, 0.5945139749; atol = 1e-4)
        @test isapprox(bg.f_pvalue, 0.5528277762; atol = 1e-6)

        # RESET powers 2:4: lm(y ~ x1+x2+yhat^2+yhat^3+yhat^4); F(3,194)
        # == lmtest::resettest(m, power=2:4, type="fitted")
        rs = reset_test(m; powers = 2:4)
        @test rs.df == (3, 194)
        @test isapprox(rs.statistic, 0.3563047032; atol = 1e-4)
        @test isapprox(rs.pvalue, 0.7846299763; atol = 1e-6)
    end

    # -------------------------------------------------------------------------
    # 2. Analytic self-consistency (needs no external tool).
    # -------------------------------------------------------------------------
    @testset "nR² identity + df" begin
        resid = m.residuals
        n = length(resid)
        x1 = X[:, 2]; x2 = X[:, 3]

        # White cross: recompute aux R² by an independent OLS-with-intercept.
        Aw = hcat(ones(n), x1, x2, x1 .^ 2, x2 .^ 2, x1 .* x2)
        bw = Aw \ (resid .^ 2)
        ew = resid .^ 2 .- Aw * bw
        d = (resid .^ 2) .- mean(resid .^ 2)
        r2w = 1 - dot(ew, ew) / dot(d, d)
        w = white_test(m; cross_terms = true)
        @test isapprox(w.statistic, n * r2w; atol = 1e-8)
        @test isapprox(w.aux_r2, r2w; atol = 1e-10)
        @test w.df == size(Aw, 2) - 1        # aux regressors excluding constant

        # BP studentized == n * R²(resid² ~ regressors).
        Ab = hcat(ones(n), x1, x2)
        bb = Ab \ (resid .^ 2)
        eb = resid .^ 2 .- Ab * bb
        r2b = 1 - dot(eb, eb) / dot(d, d)
        bp = breusch_pagan_test(m; studentized = true)
        @test isapprox(bp.statistic, n * r2b; atol = 1e-8)
        @test bp.df == 2

        # Harvey == n * R²(log resid² ~ regressors).
        lg = log.(resid .^ 2)
        bl = Ab \ lg
        el = lg .- Ab * bl
        dl = lg .- mean(lg)
        r2h = 1 - dot(el, el) / dot(dl, dl)
        h = harvey_test(m)
        @test isapprox(h.statistic, n * r2h; atol = 1e-7)
        @test h.df == 2

        # BG df == lags; RESET df1 == length(powers).
        @test breusch_godfrey_test(m; lags = 3).df == 3
        @test reset_test(m; powers = 2:5).df[1] == 4
        @test reset_test(m; powers = [2, 3]).df[1] == 2
    end

    @testset "chi-square vs F relationship (het aux F)" begin
        # For an nR² χ² statistic with p regressors, the equivalent aux F is
        #   F = (R²/p) / ((1-R²)/(n-p-1)); verify BP's implied F matches Glejser
        #   machinery via _aux_centered_r2 directly.
        resid = m.residuals
        n = length(resid)
        Z = X[:, _nonintercept_cols(X)]
        r2, df, _ = _aux_centered_r2(resid .^ 2, Z)
        @test df == 2
        Fimplied = (r2 / df) / ((1 - r2) / (n - df - 1))
        @test Fimplied > 0
        # sanity: nR² and F agree in sign of rejection region
        @test (n * r2 > quantile(Chisq(df), 0.95)) ==
              (Fimplied > quantile(FDist(df, n - df - 1), 0.95))
    end

    # -------------------------------------------------------------------------
    # 3. DISPATCH GUARD: panel breusch_pagan_test still works and coexists.
    # -------------------------------------------------------------------------
    @testset "breusch_pagan_test dispatch (RegModel vs PanelRegModel)" begin
        # RegModel method returns a RegDiagnosticResult (het test).
        r = breusch_pagan_test(m)
        @test r isa RegDiagnosticResult
        @test startswith(r.test_name, "Breusch-Pagan")

        # Panel method still returns a PanelTestResult (RE LM test) — unshadowed.
        rng = MersenneTwister(7)
        Ng, Tp = 20, 6
        n = Ng * Tp
        gid = repeat(1:Ng, inner = Tp)
        tid = repeat(1:Tp, outer = Ng)
        alpha = randn(rng, Ng)                 # entity effects -> RE present
        xp = randn(rng, n)
        yp = 1.0 .+ 0.5 .* xp .+ alpha[gid] .+ 0.3 .* randn(rng, n)
        df = DataFrame(id = gid, t = tid, y = yp, x = xp)
        pd = xtset(df, :id, :t)
        re = estimate_xtreg(pd, :y, [:x]; model = :re)
        pr = breusch_pagan_test(re)
        @test pr isa MacroEconometricModels.PanelTestResult
        @test startswith(pr.test_name, "Breusch-Pagan")
        # Two distinct methods on the same generic.
        @test !(pr isa RegDiagnosticResult)
    end

    # -------------------------------------------------------------------------
    # 4. Property / MC: size under clean DGP, power under het / serial corr.
    # -------------------------------------------------------------------------
    @testset "MC size (clean homoskedastic, iid)" begin
        reps = 400
        n = 150
        rej_white = 0; rej_bp = 0; rej_bg = 0; rej_reset = 0
        rng = MersenneTwister(4242)
        for _ in 1:reps
            xa = randn(rng, n); xb = randn(rng, n)
            yc = 0.5 .+ 1.0 .* xa .- 0.5 .* xb .+ randn(rng, n)   # homoskedastic iid
            Xc = hcat(ones(n), xa, xb)
            mc = estimate_reg(yc, Xc)
            white_test(mc).pvalue < 0.05 && (rej_white += 1)
            breusch_pagan_test(mc).pvalue < 0.05 && (rej_bp += 1)
            breusch_godfrey_test(mc; lags = 1).pvalue < 0.05 && (rej_bg += 1)
            reset_test(mc).pvalue < 0.05 && (rej_reset += 1)
        end
        # Nominal 5% — loose bands for MC noise.
        @test 0.01 < rej_white / reps < 0.12
        @test 0.01 < rej_bp / reps < 0.12
        @test 0.01 < rej_bg / reps < 0.12
        @test 0.01 < rej_reset / reps < 0.12
    end

    @testset "MC power (heteroskedastic / serially correlated)" begin
        reps = 200
        n = 200
        rng = MersenneTwister(99)
        rej_white = 0; rej_bp = 0; rej_glej = 0; rej_harv = 0; rej_bg = 0
        for _ in 1:reps
            xa = randn(rng, n)
            # Multiplicative (Harvey) heteroskedasticity, MONOTONE in xa so the
            # linear-regressor het tests (BP/Glejser/Harvey) all have power:
            # sd = exp(0.5 xa) ⇒ log(resid²) ≈ 2·0.5·xa + noise.
            u = exp.(0.5 .* xa) .* randn(rng, n)
            yc = 1.0 .+ xa .+ u
            Xc = hcat(ones(n), xa)
            mc = estimate_reg(yc, Xc)
            white_test(mc).pvalue < 0.05 && (rej_white += 1)
            breusch_pagan_test(mc).pvalue < 0.05 && (rej_bp += 1)
            glejser_test(mc).pvalue < 0.05 && (rej_glej += 1)
            harvey_test(mc).pvalue < 0.05 && (rej_harv += 1)

            # Serially correlated errors (AR(1), rho=0.7) for BG power.
            e = zeros(n); e[1] = randn(rng)
            for i in 2:n
                e[i] = 0.7 * e[i-1] + randn(rng)
            end
            ys = 1.0 .+ xa .+ e
            ms = estimate_reg(ys, Xc)
            breusch_godfrey_test(ms; lags = 1).pvalue < 0.05 && (rej_bg += 1)
        end
        @test rej_white / reps > 0.7
        @test rej_bp / reps > 0.7
        @test rej_glej / reps > 0.5
        @test rej_harv / reps > 0.7
        @test rej_bg / reps > 0.8
    end

    # -------------------------------------------------------------------------
    # 5. Display / refs / raw-data methods / guards.
    # -------------------------------------------------------------------------
    @testset "display, refs, raw methods" begin
        w = white_test(m)
        io = IOBuffer(); show(io, w); s = String(take!(io))
        @test occursin("White test", s)
        @test occursin("H0", s) || occursin("Homoskedasticity", s)
        @test occursin("Conclusion", s)

        bg = breusch_godfrey_test(m; lags = 2)
        io = IOBuffer(); show(io, bg); s = String(take!(io))
        @test occursin("Breusch-Godfrey", s)
        @test occursin("F statistic", s)      # F-form row rendered

        rstr = refs(w)
        @test occursin("White", rstr)
        @test occursin("Breusch", refs(breusch_pagan_test(m)))
        @test occursin("Ramsey", refs(reset_test(m)))
        @test occursin("Godfrey", refs(bg))

        # Raw-data (resid, X) methods agree with model methods.
        wr = white_test(m.residuals, X)
        @test isapprox(wr.statistic, w.statistic; atol = 1e-10)
        br = breusch_pagan_test(m.residuals, X)
        @test isapprox(br.statistic, breusch_pagan_test(m).statistic; atol = 1e-10)

        # Guards.
        @test_throws ArgumentError breusch_godfrey_test(m; lags = 0)
        @test_throws ArgumentError reset_test(m; powers = 1:3)
    end

    # -------------------------------------------------------------------------
    # 6. White collinearity guard: a dummy regressor's square == itself.
    # -------------------------------------------------------------------------
    @testset "White collinear-column guard (dummy regressor)" begin
        rng = MersenneTwister(11)
        n = 200
        d = Float64.(rand(rng, n) .> 0.5)          # 0/1 dummy: d^2 == d
        xc = randn(rng, n)
        yc = 1.0 .+ 0.5 .* d .+ xc .+ randn(rng, n)
        Xc = hcat(ones(n), d, xc)
        mc = estimate_reg(yc, Xc)
        w = white_test(mc; cross_terms = true)
        # Full cross design would be d,xc,d²,xc²,d·xc = 5 terms, but d²==d is
        # dropped -> df reduced. Statistic finite and valid.
        @test isfinite(w.statistic)
        @test w.statistic >= 0
        @test w.df < 5
        @test 0 <= w.pvalue <= 1
    end
end
